[build]
# Builder utilisé par Railway
builder = "dockerfile"

[deploy]
# Santé check
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Variables d'environnement par défaut
[deploy.env]
CI_ENVIRONMENT = "production"
COMPOSER_ALLOW_SUPERUSER = "1"

# Configuration du port (automatique via Railway)
[deploy.ports]
PORT = "${{PORT}}"

# Commandes personnalisées
[build.cmd]
# Build automatique des assets
run = ["npm run build:prod"]

# Configuration des volumes (optionnel)
[deploy.volumes]
# Pour la persistence des logs
"/var/www/html/writable/logs" = "logs"

# Configuration du domaine (optionnel)
[domains]
# Sera automatiquement assigné par Railway
# custom = "yourapp.railway.app"
