services:
  - type: web
    name: ci4-tailwind-template
    runtime: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm ci && npm run build:prod
    startCommand: vendor/bin/heroku-php-apache2 -C apache.conf public/
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: COMPOSER_MEMORY_LIMIT
        value: "-1"
    autoDeploy: true
    healthCheckPath: /
